# https://github.com/hashicorp/tfc-workflows-github?tab=readme-ov-file

name: "Terraform Destroy"

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "FH_Technikum"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "IaC_TFWorkshop3"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    if: github.repository != 'hashicorp-education/IaC_TFWorkshop3'
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.1 # 1.2.0 for is_destry to work
        id: destroy-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

        # https://github.com/hashicorp/tfc-workflows-github/issues/2979
      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: destroy-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.destroy-upload.outputs.configuration_version_id }}
          is_destroy: true # <-- needs to be set

      - name: Apply Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        if: fromJSON(steps.destroy-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: destroy-apply
        with:
          run: ${{ steps.destroy-run.outputs.run_id }}
          comment: "Destroy Run from GitHub Actions CI ${{ github.sha }}"
